POST http://localhost:8080/api/players HTTP/1.1
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "type": "CREATED",
  "playerId": "jdo",
  "currency":"EUR",
  "email": "john.doe@example.com",
  "firstname":"john",
  "lastname":"doe"
}

###

POST http://localhost:8080/api/players HTTP/1.1
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "type": "CREATED",
  "playerId": "aabbccc",
  "currency":"EUR",
  "email": "aabbccc@example.com",
  "firstname":"AA",
  "lastname":"BBCC"
}

###

POST http://localhost:8080/api/players HTTP/1.1
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "type": "CREATED",
  "playerId": "ThePlayer",
  "currency":"EUR",
  "email": "The.player@example.com",
  "firstname":"The",
  "lastname":"Player"
}

###
