apiVersion: v1
kind: Service
metadata:
  name: jpa-cockroachdb-svc
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jpa-cockroachdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jpa-cockroachdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpa-cockroachdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jpa-cockroachdb
        date: 2017-10-16
    spec:
      imagePullSecrets:
        - name: artifactory
      containers:
      - name: jpa-cockroachdb
        image: docker-repo.repo.lottoland.io/dreamit/jpa-cockroachdb:1.0-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROJECT_STAGE
          value: SystemTest
        - name: JVM_OPTIONS
          value: -Dkafka.servers=cockroachdb:26257
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 30
